apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: efqzztm7i-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:fd1f25df295716d71f71ff29f3448794e71a0d13@sha256:4148ec166e7dd3a9f541344ce2d4b59142ce6905d1dcef44bad8458e3bb2ba94
          name: container-image
